sudo: required
services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

language: python
python: 3.6
cache: pip

install: pip install -r requirements_test.txt

script: dependencies test -s
